name: Deploy & Restart

on:
  push:
    branches: [ "main", "master" ]

jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: Send Restart Signal
        run: |
          curl -X POST \
            "${{ secrets.PTERODACTYL_HOST }}/api/client/servers/${{ secrets.PTERODACTYL_SERVER_ID }}/power" \
            -H "Authorization: Bearer ${{ secrets.PTERODACTYL_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d '{"signal": "restart"}'
